#lang simply-scheme

(require rackunit)

(define (make-account1 balance)
  (define init balance)
  (define record '())
  (define (withdraw amount)
    (set! record (append record (list (list 'withdraw amount))))
    (set! balance (- balance amount)) balance)
  (define (deposit amount)
    (set! record (append record (list (list 'deposit amount))))
    (set! balance (+ balance amount)) balance)
  (define (dispatch msg)
    (cond
      ((eq? msg 'balance) balance)
      ((eq? msg 'init-balance) init)
      ((eq? msg 'withdraw) withdraw)
      ((eq? msg 'deposit) deposit)
      ((eq? msg 'transactions) record)) )
  dispatch)

(define (make-account2 init-amount)
  (let ((balance init-amount)
        (record '()))
    (define (withdraw amount)
      (set! record (append record (list (list 'withdraw amount))))
      (set! balance (- balance amount)) balance)
    (define (deposit amount)
      (set! record (append record (list (list 'deposit amount))))
      (set! balance (+ balance amount)) balance)
    (define (dispatch msg)
      (cond
        ((eq? msg 'balance) balance)
        ((eq? msg 'init-balance) init-amount)
        ((eq? msg 'withdraw) withdraw)
        ((eq? msg 'deposit) deposit)
        ((eq? msg 'transactions) record)) )
    dispatch) )

(define acc1 (make-account1 100))
(check-equal? ((acc1 'withdraw) 50) 50)
(check-equal? ((acc1 'deposit) 10) 60)
(check-equal? (acc1 'transactions) '((withdraw 50) (deposit 10)))

(define acc2 (make-account2 100))
(check-equal? ((acc2 'withdraw) 50) 50)
(check-equal? ((acc2 'deposit) 10) 60)
(check-equal? (acc2 'transactions) '((withdraw 50) (deposit 10)))